
[tool.poetry]
name = "bankstat-dashboard"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.11"
streamlit = ">=1.28.0"
pandas = ">=1.5.0"
plotly = ">=5.15.0"
plotly-express = ">=0.4.1"
requests = ">=2.31.0"
python-dotenv = ">=1.0.0"
pymongo = ">=4.5.0"
lxml = ">=5.4.0"
psycopg2-binary = "*"
streamlit-authenticator = "*"
streamlit-mermaid = "*"
propelauth-py = "*"
authlib = "*"
scikit-learn = "*"
tensorflow-cpu = "*"
cerebras-cloud-sdk = "*"
sqlalchemy = "*"
supabase = "*"

[tool.poetry.group.dev.dependencies]
mypy = "*"
flake8 = "*"
black = "*"
isort = "*"
