#place this inside .streamlit

[database]
db_username = "YOUR_DB_USERNAME"
db_password = "YOUR_DB_PASSWORD"
mongodb_url = "YOUR_MONGODB_URL"

[upstage]
api_key = "YOUR_UPSTAGE_API_KEY"

[auth]
client_id = "YOUR_PROPELAUTH_CLIENT_ID"
api_key = "YOUR_PROPELAUTH_API_KEY"
client_secret = "YOUR_PROPELAUTH_CLIENT_SECRET"
auth_url = "YOUR_PROPELAUTH_AUTH_URL"
server_metadata_url = "YOUR_PROPELAUTH_AUTH_URL/.well-known/openid-configuration"
redirect_uri = "http://localhost:8501/oauth2callback"
cookie_secret = "YOUR_RANDOM_COOKIE_SECRET"

#generate cookie_secret with python -c "import os; print(os.urandom(24).hex())"
